#!/bin/bash

set -euo pipefail

echo "~~~ Init Hermit environment"
if ! . bin/activate-hermit; then
  echo "Failed to initialize Hermit environment"
  exit 1
fi

export PATH="$PATH:/var/lib/buildkite-agent/bin"
